# Generated by Django 5.2.1 on 2025-06-15 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='content',
        ),
        migrations.AddField(
            model_name='notification',
            name='edited',
            field=models.BooleanField(default=False, help_text='Message edited'),
        ),
        migrations.AddField(
            model_name='notification',
            name='edited_at',
            field=models.DateTimeField(blank=True, help_text='Last edited', null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False, help_text='Message Read'),
        ),
    ]
